### PR TITLE
introduce tarjan's algorithm (#103)

### PR DESCRIPTION
**Pull request by suncanghuai**
* implement tarjan's algorithm to find scc for directed graphs
* implement tarjan's algorithm to find cut vertices/bridges/V-Dcc/E-Dcc for undirected graphs
* formatting

There might be different purposes of Tarjan's algorithm, but the basic framework and core idea of it are the same. So I implemented a common function for Tarjan's algorithm which return different results based on the input parameter instead of multiple slightly modified versions of that.

### CODE REVIEW

**Comment by suncanghuai** [comment]
This work is not done yet as I've been too busy recently writing test cases and making sure my submission is bug-free. I opened this PR not wanting this submission to be merged now, but to share my progress with you guys @ZigRazor. Testing work and bug fixes are expected to be finished in the next few weeks.

**Comment by ZigRazor** [comment]
Ok @suncanghuai I convert this to draft PR until it will be completed

**Comment by suncanghuai** [comment]
@ZigRazor, Tarjan's algorithm was fully tested. I think it's time to merge it.

**Review by ZigRazor — APPROVED** [review]
Good work!

**Pull request merged**
