### PR TITLE
Refactoring: writeToStandardFile and readFromStandardFile

### PR DESCRIPTION
**Pull request by pavan-pan**
Resolves Refactoring: writeToStandardFile_tsv and writeToStandardFile_csv #168
- The readFromStandardFile_csv and readFromStandardFile_tsv is replaced with readFromStandardFile() with an additional parameter of type InputOutputFormat. 
- The writeToStandardFile_csv and writeToStandardFile_tsv is replaced with writeToStandardFile() with an additional parameter of type InputOutputFormat.

@ZigRazor @AlfredCP @sidml

### CODE REVIEW

**Comment by pavan-pan** [comment]
Hi guys, sorry for the mess in this pr. I changed my mind about certain things later on.
Also, again 2 checks failed above. Not sure why this is happening. 
@ZigRazor @AlfredCP @sidml

**Review by ZigRazor — APPROVED** [review]
good job!

**Comment by ZigRazor** [comment]
@pavan-pan  I invite you as collaborator

**Comment by ZigRazor** [comment]
> Hi guys, sorry for the mess in this pr. I changed my mind about certain things later on. Also, again 2 checks failed above. Not sure why this is happening. @ZigRazor @AlfredCP @sidml

benchmark is not working! and the coverage is only decreased by a little %

**Comment by pavan-pan** [comment]
Thanks @ZigRazor

**Pull request merged**
