### PR TITLE
Reorganizzation of Code

### PR DESCRIPTION
**Pull request by ZigRazor**
These modifies does not broke the interfaces, but are significatly reworked the organizations of files.
This PR is related also to issue #364

### CODE REVIEW

**Review by sbaldu — APPROVED** [review]
Looks good to me. I think it's a good idea to separate declarations and implementations, and also to put every algorithm in a single header. It will be much easier and quicker to find stuff now.

**Comment by sbaldu** [comment]
Just out of curiosity, why are some files `.h` and others `.hpp`?

**Comment by ZigRazor** [comment]
> Just out of curiosity, why are some files `.h` and others `.hpp`?

Because the `.h` file contains only declaration, and the `.hpp` file contains the template implementations

**Comment by sbaldu** [comment]
> > Just out of curiosity, why are some files `.h` and others `.hpp`?
> 
> Because the `.h` file contains only declaration, and the `.hpp` file contains the template implementations

Ok thanks

**Pull request merged**
