### PR TITLE
Feature import/export with dot files

### PR DESCRIPTION
**Pull request by sbaldu**
Implementation of methods for the Graph class which allow to construct a graph by importing it from a DOT file or to export it to a DOT file (#244).

### CODE REVIEW

**Comment by ZigRazor** [comment]
please resolve conflict, or we can't continue.
Thank you!

**Review by ZigRazor — APPROVED** [review]

**Review by nrkramer — APPROVED** [review]
Hey @sbaldu, thanks for opening this PR! So far the changes look fantastic.

The conflict is because I recently changed the root-level namespace to title-case.

**Comment by sbaldu** [comment]
@nrkramer Hi, I'm glad you like the changes.
I've merged your changes in my branch and now it should be fine.

**Comment by nrkramer** [comment]
Merge LGTM

**Pull request merged**
