### PR TITLE
Add tests for cycles in directed graphs

### PR DESCRIPTION
**Pull request by sbaldu**
Add tests to the GraphTest testcase to check that the hashing function used for the sets of edges doesn't cause problems with directed edges forming a cycle (issue #324)

### CODE REVIEW

**Comment by ZigRazor** [comment]
Sorry @sbaldu , these test are passed?

**Comment by sbaldu** [comment]
> Sorry @sbaldu , these tests are passed?

Yes they both pass

**Review by nrkramer — APPROVED** [review]

**Comment by nrkramer** [comment]
Looks good. Thanks @sbaldu !! This definitely closes the issue out.

**Comment by ZigRazor** [comment]
I merge this PR even if the problem reported in #324 and the demostration on PR #326 is not solver.
In any case this PR add some tests, that are correct.

**Comment by sbaldu** [comment]
Ok @ZigRazor, thanks

**Pull request merged**
