### PR TITLE
Add structs default niitial values

### PR DESCRIPTION
**Pull request by AlfredCP**
- Resolves https://github.com/ZigRazor/CXXGraph/issues/158
- Added initial values for the different structs and member variables not to have unexpected behaviors.

### CODE REVIEW

**Comment by sidml** [comment]
LGTM :-)

**Review by ZigRazor — COMMENTED** [review]
why you add initial value in the declaration and not in the constructor?

**Comment by AlfredCP** [comment]
I added those values as "default member initializer" because I don't see the need of defining any constructor.
Also, in case we define several constructors, we don't need to define all those variables in all of them unless we want a different initial value.

I think in the end there is no difference, both possibilities are correct and will work for what we want.
Just I don't see the difference of defining the default constructor, the compiler will do it better than me for sure   :)

I checked it and seems that both solutions are good for us.
https://en.cppreference.com/w/cpp/language/data_members#Member_initialization

**Comment by AlfredCP** [comment]
Liked your question, it made me to investigate a bit about those 2 possibilities

**Review by ZigRazor — APPROVED** [review]

**Pull request merged**
