### PR TITLE
Website documentation

### PR DESCRIPTION
**Pull request by morelmiles**
Discussion #200  about the website
Tasks 
[x] - Add examples 
[x] - Add installation and uninstallation guidelines

### CODE REVIEW

**Comment by ZigRazor** [comment]
I could not build site with these errors:

```
[WARNING] Docs markdown link couldn't be resolved: (./create-a-page.md) in /workspaces/WEBSITE/CXXGraph/website/docs/installation-guidelines/markdown-features.mdx for version current
[WARNING] Docs markdown link couldn't be resolved: (./create-a-page.md) in /workspaces/WEBSITE/CXXGraph/website/docs/installation-guidelines/markdown-features.mdx for version current
[ERROR] Docusaurus server-side rendering could not render static page with path /404.html.
[ERROR] Docusaurus server-side rendering could not render static page with path /markdown-page.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/examples/Dial.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/examples/Dijkstra.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstall/DEB.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstall/Install From Source.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstall/Linux Turballs.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstall/RPM.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstall/Unit Test Execution.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstallation/DEB.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstallation/Install From Source.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstallation/Linux Turballs.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstallation/RPM.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-and-uninstallation/Unit Test Execution.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-guidelines/markdown-features.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/installation-guidelines/new.
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/intro.
[ERROR] Docusaurus server-side rendering could not render static page with path /.
```

**Comment by ZigRazor** [comment]
@morelmiles  I found the problem:
In `docusaurus.config.js` there is a reference to "Intro" while the docId is "intro".
While you can correct this, you can also do a spellcheck for linux "Turballs" that should be "Tarballs"

**Comment by morelmiles** [comment]
hey @ZigRazor, 
sorry about the error `intro` error. had forgotten that i had to update through the docs. 
also,  fixed the spelling error. 

have a look ans let me know what you think.

**Review by ZigRazor — APPROVED** [review]

**Comment by ZigRazor** [comment]
@morelmiles  ALL OK!
please resolve the conflict to merge the pull request!

**Comment by ZigRazor** [comment]
results ever in conflict...

**Comment by morelmiles** [comment]
trying to resolve them.


---
Luigi Morel.

Software Engineer

Tel: +256 704 916 696 (WhatsApp only)

**Comment by morelmiles** [comment]
hey @ZigRazor, the conflicts have been resolved.

**Comment by ZigRazor** [comment]
Thank you!

**Comment by morelmiles** [comment]
Are you able to run the site locally?

**Comment by ZigRazor** [comment]
@morelmiles yes, i'm able

**Pull request merged**
