### PR TITLE
Bron kerbosch

### PR DESCRIPTION
**Pull request by danrr02**
#381 - Introduce Bron-Kerbosch Algorithm

- Current implementation is of the basic algorithm without pivots but I would be happy to update to using pivots if requested.

### CODE REVIEW

**Review by ZigRazor — APPROVED** [review]
GOOD JOB!

**Review by ZigRazor — APPROVED** [review]

**Comment by ZigRazor** [comment]
@danrr02  the test build fails, can you correct it?

**Comment by danrr02** [comment]
> @danrr02 the test build fails, can you correct it?

Hi, @ZigRazor 

I have some questions about which builds you would like me to correct, and how I might go about doing that:

1. The build which fails in CodeQL is failing due to an error in examples/NetworkDynamicsExample/network_dynamics_example.cpp:

error: invalid initialization of reference of type ‘const std::vector<int>&’ from expression of type ‘const unsigned int’
   29 |     const std::vector<int>& degrees = nodePair.second;

If this is the build which you referred to in your comment how would you like me to proceed? I have not interacted with this file at all so I do not want to prematurely attempt to resolve the error without being specifically requested to do so.


2. The build which fails in CMake/build (windows-latest) will be difficult for me to resolve as I do not have access to a windows machine. If there is another way I can attempt to correct this I would appreciate any advice.


3. I am also struggling to resolve the ctest failures in CMake/build(ubuntu-latest) and CMake/build(macos-latest) as I do not see the errors when running ctest in my local build/test directory.


Sorry for asking so many questions, but I just want to make sure everything is done properly.

Thanks,
danrr02

**Comment by ZigRazor** [comment]
@danrr02 sorry was a problem with the new version of Ctest, I correct the workflow.
We can merge it!

**Review by ZigRazor — APPROVED** [review]

**Pull request merged**
